# Generated by Django 4.0.3 on 2022-03-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_alter_testprogress_date_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testprogress',
            name='time_end',
        ),
        migrations.AlterField(
            model_name='testprogress',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время конца'),
        ),
    ]
