# Generated by Django 3.2.3 on 2022-04-06 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_remove_testprogress_time_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='Номер урока')),
                ('id_message', models.IntegerField(verbose_name='Номер сообщения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.telegramuser')),
            ],
        ),
    ]
